#ifndef ERRORS_H
#define ERRORS_H

#define ERR_SUCCESS 0
#define ERR_SER_ARG_MISSING -1
#define ERR_SER_ARG_ILLEGAL -2

#define ERR_MEMPOOL_CREATE_FILE -3
#define ERR_MEMPOOL_HOST_EXIST -4
#define ERR_MEMPOOL_NULL_PTR -5

#endif //ERRORS_H
